

protoc:
	protoc --go_out=module=github.com/dgodyna/protoc-gen-deepcopy/pkg/internal/examples:. simple.proto
	protoc --resource_out=module=github.com/dgodyna/protoc-gen-deepcopy/pkg/internal/examples:. simple.proto