// Code generated by protoc-gen-deepcopy. DO NOT EDIT.

package examples

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ABitOfScalars) DeepCopyInto(out *ABitOfScalars) {
	in.DoubleType = out.DoubleType
	in.FloatType = out.FloatType
	in.Int32Type = out.Int32Type
	in.Int64Type = out.Int64Type
	in.Uint32Type = out.Uint32Type
	in.Uint64Type = out.Uint64Type
	in.Sint32Type = out.Sint32Type
	in.Sint64Type = out.Sint64Type
	in.Fixed32Type = out.Fixed32Type
	in.Fixed64Type = out.Fixed64Type
	in.Sfixed32Type = out.Sfixed32Type
	in.Sfixed64Type = out.Sfixed64Type
	in.BoolType = out.BoolType
	in.StringType = out.StringType
	in.BytesType = out.BytesType
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *ABitOfScalars) DeepCopy() *ABitOfScalars {
	if in == nil {
		return nil
	}
	out := new(ABitOfScalars)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, returning deepcopy as runtime.Object interface.
func (in *ABitOfScalars) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
