name: Go
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: golang
    steps:
    - uses: actions/checkout@v2
    - run: | go install github.com/bazelbuild/bazelisk@latest
        bazelist test //...
  build:
    runs-on: golang
    steps:
    - uses: actions/checkout@v2
    - uses: bazelbuild/setup-bazelisk@v1
    - run: | go install github.com/bazelbuild/bazelisk@latest
        bazelist build //...